### ISSUE TITLE
Rename Assigned Site when editing Equipment Type Info

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#10]
Rename "Not Assigned0" to "Not Assigned"

Steps to recreate:
Click on Equipment
Click on any Equipment Serial Number
Change Assigned Site. 
![image](https://cloud.githubusercontent.com/assets/17583549/24162714/a79011fe-0e25-11e7-9205-5506afb0b8b8.png)

**Comment by alvinquach** [comment]
fixed
