### ISSUE TITLE
Status of soil and water when adding repair data

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#12]
When checking soil or leaving the check boxes blank, will result in Soil = false and Water = blank

Steps to recreate:
Go to IME numbers
Go click on an IME# 
Click Add repair data, Do not check Soil and Water. Or you can just check soil. It has the same result. 
Click save. 
Only boolean for soil comes out and not water. 
(works when you check water, soil = false, water = true

![image](https://cloud.githubusercontent.com/assets/17583549/24164091/d929ed08-0e29-11e7-8528-5b3fa5da825e.png)

**Comment by alvinquach** [comment]
LOOOL wtf

**Comment by alvinquach** [comment]
Fixed. Will be deployed with 0.0.8-SNAPSHOT.
