### ISSUE TITLE
Fields disappearing when trying to verify data

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#13]
Steps to recreate: 
Go to Unverified Data Sets
Edit 1st unverified data. 
Change any fields. 
Will say no errors. 
Save. Site, grid and error disappears. 
If you press commit/save again, web app stops functioning.
![image](https://cloud.githubusercontent.com/assets/17583549/24164257/54b1fb1e-0e2a-11e7-84bc-301a9ce8fef4.png)

![image](https://cloud.githubusercontent.com/assets/17583549/24164488/22807f2a-0e2b-11e7-9efd-452fc7d1267c.png)

**Comment by alvinquach** [comment]
woah

**Comment by alvinquach** [comment]
No longer applicable. Entire page has been reworked.
