### ISSUE TITLE
Transition when registering a new user

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#15]
When registering a new user, after confirmation, it does not close the form. If you press confirm again, you will get an exception. The user will still be added though. 

![image](https://cloud.githubusercontent.com/assets/17583549/24188098/3805ad26-0e9d-11e7-9987-233bd34acc4c.png)

**Comment by alvinquach** [comment]
Broken in latest release due to JSON deserializer no longer accepting password field. Will fix soon.

**Comment by alvinquach** [comment]
Fixed. Will be deployed with 0.0.8-SNAPSHOT.
