### ISSUE TITLE
When uploading data, you do not get a chance to verify

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#16]
Once you upload the data, you will be directed to the verify data page, but there is nothing on it. 
The data will be in the unverified data sets page. If there is an IME, it will also be stored in IME Numbers.

Steps to recreate:
Go to Upload from Mobile
Upload the JSON file
wait endlessly

![image](https://cloud.githubusercontent.com/assets/17583549/24209793/7776e8a2-0ee4-11e7-87c8-9eefdf3fcbaa.png)

**Comment by alvinquach** [comment]
This is caused by redirecting to the wrong page (a non-existent unverified data set) after successful upload. User should instead be redirected to the unverified data set _list_ page.

**Comment by alvinquach** [comment]
Fixed. Will be deployed with 0.0.8-SNAPSHOT.
