### ISSUE TITLE
Adding blank spaces for User group is valid

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#6]
When adding a user group, a space bar is valid input. Maybe change it to alphanumeric?

Steps to reproduce:
Click on User Groups
Click on New Group
put "  " as Group Name
Submit

![image](https://cloud.githubusercontent.com/assets/17583549/24161948/1e6dc9d6-0e23-11e7-9799-5ea12bfe4113.png)

**Comment by alvinquach** [comment]
Fixed. Will be deployed with 0.0.8-SNAPSHOT.
