### ISSUE TITLE
Cannot view User or User Group Details on a new tab

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#7]
Steps to recreate:
Go to Users
Crtl+Click a user, should put it in a new tab.
Wait for the information to load. (It won't.)

![image](https://cloud.githubusercontent.com/assets/17583549/24162184/eb435692-0e23-11e7-89e9-6890debd1576.png)

**Comment by alvinquach** [comment]
This is an issue with storing the JWT in the sessionStorage, as data in the sessionStorage is not shared between tabs. Will need to revert back to localStorage to fix this issue.

**Comment by alvinquach** [comment]
should be fixed
