### ISSUE TITLE
Add error checking when adding the same instrument and new instruments

### ISSUE THREAD

**Issue by chrisOw131** [landfill-eforms/landfill-web-app#9]
Do not let the user add the same equipment if it is already on the list. 
Do not let the user put special characters and spaces as serial number (i.e ! or "  ")

Steps on how to recreate:
Go to Equipment
Go press the + button
Serial number type: " "
Any Equipment Type
Any Status 
Confirm

**Comment by alvinquach** [comment]
Fixed. Will be deployed with 0.0.8-SNAPSHOT.
